### ISSUE TITLE
BEM results include all iterations

### ISSUE THREAD

**Issue by mjanszen** [mjanszen/RotorWakeAerodynamicsBEM#1]
In the final df_results of the bem object, all iterations are saved, such that plotting requires to select only the last entries. Is that a functionality that we want? @JonasMPN

**Comment by JonasMPN** [comment]
By iterations, I understand the iterations of the convergence loop for the induction factors. I am assuming you mean something else, as the values of those iterations are not saved to df_results.

Each call to solve() saves the final converged results to df_results. These results contain the specifications and results of each blade element.
